site_name: Freifunk Dokumentation
site_url: https://tbuss.github.io/ff3l-docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy